### ISSUE TITLE
Website Image Optimization

### ISSUE THREAD

**Issue by abdul-muyeed** [abdul-muyeed/abdul-muyeed.github.io#1]
You will find all the images in the images folder [path](https://github.com/abdul-muyeed/abdul-muyeed.github.io/tree/main/images)

**Convert images from jpg to webp format and compress the memory size without losing quality.**

**PR guideline:**
1. Fork the repo
2. Make a comment on the issue to inform me that you are working on it
3. Clone the repo
4. Make a new branch
5. Make changes
6. add, commit and push the new branch
7. Make the pull request

**Note:** any pr to the main branch will be rejected.

**Comment by ronitsharma03** [comment]
Hey  @abdul-muyeed  Can you assign this to me?

**Comment by abdul-muyeed** [comment]
Yes, I am here to help.

**Comment by ronitsharma03** [comment]
Can i start working on it
?

**Comment by abdul-muyeed** [comment]
Yes.

**Comment by ronitsharma03** [comment]
What major changes you want me to do?

**Comment by abdul-muyeed** [comment]
just convert images from jpg format to webp.

**Comment by ronitsharma03** [comment]
Okay

**Comment by ronitsharma03** [comment]
Hey @abdul-muyeed  i can't upload to this branch

**Comment by abdul-muyeed** [comment]
Use a #1 in the title of the pr
